package cmd

import (
	"context"
	"fmt"
	"log"

	"github.com/hanifanmoha/go-explore/_midsize-project/semantic-search/pkg/helper"
	"github.com/hanifanmoha/go-explore/_midsize-project/semantic-search/services"
	"github.com/spf13/cobra"
)

var SearchCmd = &cobra.Command{
	Use:   "search",
	Short: "Search for relevant information using embeddings",
	Long:  `Search for relevant information using embeddings generated by the Gemini API`,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("Search embeddings...")
		processSearch()
	},
}

func processSearch() {

	helper.LoadEnv()

	genaiSvc, err := services.NewGenAIService()
	if err != nil {
		log.Println("Error initializing GenAI service:", err)
		return
	}

	dbConnection, err := services.NewDatabaseService()
	if err != nil {
		log.Println("Error connecting to database:", err)
		return
	}
	defer dbConnection.Close()

	text := "Jason Bourne actor also played in other movies, where he played as an astronaut"

	vector, err := genaiSvc.GenerateEmbedding(text, services.TaskTypeRetrievalQuery)
	if err != nil {
		log.Printf("Error generating embedding for query: %v\n", err)
		return
	}

	results, err := dbConnection.SearchEmbeddings(context.Background(), vector, 5)
	if err != nil {
		log.Printf("Error searching embeddings in database: %v\n", err)
		return
	}

	log.Printf("Search results for query: %s\n", text)
	for _, result := range results {
		log.Printf("ID: %d, Topic: %s, Name: %s\n", result.ID, result.Topic, result.Name)
	}

}
